name: CI

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run changed-files with dir_names
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          dir_names: true
          matrix: true
      - name: List all changed directories
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  validate:
    runs-on: ubuntu-latest
    needs: changed-files
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Check commit message
        uses: wagoid/commitlint-github-action@v6
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
      - name: Tofu Fmt
        run: tofu fmt -check
        working-directory: ${{ matrix.dir }}
      - name: Tofu Init
        run: tofu init
        working-directory: ${{ matrix.dir }}
      - name: Tofu Validate
        run: tofu validate -no-color
        working-directory: ${{ matrix.dir }}
